# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PrintableMapTools
                                 A QGIS plugin
 "Pintable Map Tools" is a plugin under development for QGIS. The goal is to create modules and enhancements for printable maps, including label placement.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-07-11
        copyright            : (C) 2020 by STADTKREATION
        email                : qgis@stadtkreation.de
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PrintableMapTools class from file PrintableMapTools.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .printable_map_tools import PrintableMapTools
    return PrintableMapTools(iface)
